import Footer from "@/components/footer"
import Header from "@/components/header"

export const metadata = {
  title: 'Virtual Lab',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
